spring.application.name=MentorConnect
spring.datasource.url=jdbc:mysql://localhost:3306/mentorconnect?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=hemasri2007selvakumar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
